// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:suito/features/transaction/infrastructure/models/transaction_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BitcoinSnapshotHiveModelAdapter());
    registerAdapter(TransactionHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BitcoinSnapshotHiveModelAdapter());
    registerAdapter(TransactionHiveModelAdapter());
  }
}
