// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `find_pair_rate`, `rounded_div_positive`, `sat_to_jpy`, `sat_to_usd_cents`, `validate_sat_amount`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// `sat_amount` とネットワークから取ったレートでスナップショットを組み立てる。
Future<BuiltBitcoinRecordSnapshot> buildBitcoinRecordSnapshotFromSat({
  required PlatformInt64 satAmount,
}) => RustLib.instance.api.crateApiBitcoinBuildBitcoinRecordSnapshotFromSat(
  satAmount: satAmount,
);

/// Dart `BitcoinRecordSnapshot` に対応するフラット型。
class BuiltBitcoinRecordSnapshot {
  final PlatformInt64 satAmount;
  final PlatformInt64 jpyAtRecordTime;
  final PlatformInt64 usdCentsAtRecordTime;
  final PlatformInt64 btcJpyRate;
  final PlatformInt64 btcUsdCentRate;
  final PlatformInt64 recordedAtMillisSinceEpochUtc;

  const BuiltBitcoinRecordSnapshot({
    required this.satAmount,
    required this.jpyAtRecordTime,
    required this.usdCentsAtRecordTime,
    required this.btcJpyRate,
    required this.btcUsdCentRate,
    required this.recordedAtMillisSinceEpochUtc,
  });

  @override
  int get hashCode =>
      satAmount.hashCode ^
      jpyAtRecordTime.hashCode ^
      usdCentsAtRecordTime.hashCode ^
      btcJpyRate.hashCode ^
      btcUsdCentRate.hashCode ^
      recordedAtMillisSinceEpochUtc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuiltBitcoinRecordSnapshot &&
          runtimeType == other.runtimeType &&
          satAmount == other.satAmount &&
          jpyAtRecordTime == other.jpyAtRecordTime &&
          usdCentsAtRecordTime == other.usdCentsAtRecordTime &&
          btcJpyRate == other.btcJpyRate &&
          btcUsdCentRate == other.btcUsdCentRate &&
          recordedAtMillisSinceEpochUtc == other.recordedAtMillisSinceEpochUtc;
}
