// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `btc_jpy_yen_from_ticker`, `btc_usd_cents_from_dollars_f64`, `build_http_client`, `fetch_btc_jpy`, `fetch_btc_usd`, `fetch_usd_jpy`, `get_json_once`, `json_to_positive_f64`, `kraken_best_btc_usd_dollars`, `parse_bitflyer_btc_jpy`, `parse_coinbase_btc_usd`, `parse_coincheck_btc_jpy`, `parse_frankfurter_usd_jpy`, `parse_kraken_btc_usd`, `parse_open_er_usd_jpy`, `retrying_get_json`, `usd_jpy_yen_rate_from_rates_map`, `utc_now_millis_i64`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// すべての標準ペア（BTC/JPY・BTC/USD cents・USD/JPY）を一括で取得する。
///
/// HTTP 処理はすべてここ経由でのみ実行され、Dart 側はこの関数を単に呼ぶ。
Future<List<FetchedExchangeRate>> fetchExchangeRatesFromNetwork() =>
    RustLib.instance.api.crateApiExchangeFetchExchangeRatesFromNetwork();

/// Dart 側の Domain `ExchangeRate` に対応させやすいフラット構造体。
///
/// - [pair_key]: `BTC_JPY` / `BTC_USD` / `USD_JPY`。
/// - [rate]: 「from の 1 major 単位」を「to の minor 単位で何個」に換算する値。
class FetchedExchangeRate {
  final String pairKey;
  final PlatformInt64 rate;
  final PlatformInt64 fetchedAtMillisSinceEpochUtc;
  final String? source;

  const FetchedExchangeRate({
    required this.pairKey,
    required this.rate,
    required this.fetchedAtMillisSinceEpochUtc,
    this.source,
  });

  @override
  int get hashCode =>
      pairKey.hashCode ^
      rate.hashCode ^
      fetchedAtMillisSinceEpochUtc.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FetchedExchangeRate &&
          runtimeType == other.runtimeType &&
          pairKey == other.pairKey &&
          rate == other.rate &&
          fetchedAtMillisSinceEpochUtc == other.fetchedAtMillisSinceEpochUtc &&
          source == other.source;
}
