// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_keys`

/// NIP-44 v2 で **自分の公開鍵宛て** に暗号化する（同期用ペイロード向け）。
///
/// `encrypt(sender_sk, recipient_pk, ...)` で `recipient_pk == sender_pk` と等价。
Future<String> nostrNip44EncryptV2ForSelf({
  required String plaintext,
  required String secretKey,
}) => RustLib.instance.api.crateApiNostrNostrNip44EncryptV2ForSelf(
  plaintext: plaintext,
  secretKey: secretKey,
);

/// [nostr_nip44_encrypt_v2_for_self] の逆。イベント検証後に呼ぶこと（NIP-44 要件）。
Future<String> nostrNip44DecryptV2FromSelf({
  required String ciphertext,
  required String secretKey,
}) => RustLib.instance.api.crateApiNostrNostrNip44DecryptV2FromSelf(
  ciphertext: ciphertext,
  secretKey: secretKey,
);

/// 平文 JSON を NIP-44 v2 で包み、`kind 30100` + `d` タグの署名済みイベント JSON を返す。
///
/// - `json_payload`: 暗号化前の UTF-8 文字列（通常は取引 JSON）。
/// - `d_tag_identifier`: パラメトリックイベントの決定的 ID（重複時差し替え用）。
Future<String> nostrSignEncryptedReplaceableEvent({
  required String jsonPayload,
  required String secretKey,
  required String dTagIdentifier,
}) => RustLib.instance.api.crateApiNostrNostrSignEncryptedReplaceableEvent(
  jsonPayload: jsonPayload,
  secretKey: secretKey,
  dTagIdentifier: dTagIdentifier,
);

/// NIP-01 署名・鍵形式の検証（復号前に必須、NIP-44）。
Future<void> nostrVerifyEventJson({required String eventJson}) => RustLib
    .instance
    .api
    .crateApiNostrNostrVerifyEventJson(eventJson: eventJson);
